'use strict';
// Final Part uses the original Desktop window manager but its own story and storage.
// Progress is isolated; the chapter's restart link restores the demonstration cue.
window.FinalPart = (() => {
 const apps = {
  log:{name:'Work Log',w:790,h:610},manager:{name:'Workspace',w:800,h:570},
  queue:{name:'Assigned files',w:780,h:570},targets:{name:'Performance',w:640,h:530},
  calendarWork:{name:'Work calendar',w:640,h:530},policy:{name:'Device management',w:620,h:530},
  archive:{name:'Personal — archived',w:730,h:560},photosOld:{name:'Photos — unavailable',w:600,h:440},
  musicOld:{name:'Music — unavailable',w:600,h:440},gamesOld:{name:'Games — removed',w:600,h:440}
 };
 const kinds=['Project report','Morning summary','Meeting notes','Client revisions','Delivery checklist','Status update'];
 const files=Array.from({length:60},(_,i)=>({id:`file-${i}`,name:`${kinds[i%6]}_${i<12?'v'+(18+i):i<24?'final_'+(i-11):'final_REVISED_'+(i-23)}.${i%6===1?'xlsx':'docx'}`}));
 for(const f of files)apps[f.id]={name:f.name,w:670,h:530};
 const f={submitted:false,saved:false,reviewed:false,cycle:0,clock:'17:20',target:100,score:99,contact:'manager',reply:false,draft:'',busy:false,notificationRead:false};
 if(!new URLSearchParams(location.search).has('restart')){
  const saved=state.finalStory;
  if(saved&&[100,120].includes(saved.target)&&Number.isInteger(saved.score)&&saved.score>=0&&saved.score<=120&&Number.isInteger(saved.cycle)&&saved.cycle>=0&&typeof saved.draft==='string'&&['17:20','09:00'].includes(saved.clock)&&['submitted','saved','reviewed','reply','notificationRead'].every(k=>typeof saved[k]==='boolean'))Object.assign(f,saved,{busy:false});
 }
 let noticeTimer=null;
 const esc=escapeHTML;
 const symbol=id=>({log:'document',manager:'office',queue:'files',targets:'office',calendarWork:'calendar',policy:'settings',archive:'chat',photosOld:'photos',musicOld:'music',gamesOld:'games'}[id]||'document');
 const button=(id,label,cls='btn')=>`<button class="${cls}" data-final="open" data-id="${id}">${label}</button>`;
 const metric=()=>`${f.score} / ${f.target}`;
  function place(w){
  const base={log:[310,110],manager:[430,165],queue:[190,80],targets:[560,120],archive:[360,125]};
  const xy=base[w.app]||[280+(Desktop.comp().windows.length%5)*30,95+(Desktop.comp().windows.length%5)*28];
  w.x=Math.min(xy[0],Math.max(10,innerWidth-w.w-30));w.y=xy[1];
 }
 function chrome(){
  const shortcuts=document.getElementById('shortcuts');
  const order=['log','manager','queue','targets','calendarWork','policy',...files.slice(0,36).map(x=>x.id),'archive','photosOld','musicOld','gamesOld',...files.slice(36).map(x=>x.id)];
  if(!shortcuts.children.length)shortcuts.innerHTML=order.map(id=>`<button class="desktop-shortcut ${['archive','photosOld','musicOld','gamesOld'].includes(id)?'personal-remnant':''}" data-launch="${id}" aria-label="${esc(apps[id].name)}" title="Double-click to open ${esc(apps[id].name)}">${WinShell.appIcon(symbol(id))}<span>${esc(apps[id].name)}</span>${id==='manager'?'<b class="shortcut-badge">12</b>':''}</button>`).join('');
  shortcuts.style.gridTemplateRows=`repeat(${Math.max(3,Math.floor((innerHeight-150)/97))},91px)`;
  const badge=shortcuts.querySelector('.shortcut-badge');if(badge)badge.hidden=f.notificationRead;
  const comp=Desktop.comp(), pinned=['log','manager','queue','targets','calendarWork'];
  const tabs=[...pinned,...comp.windows.filter(w=>!pinned.includes(w.id)).map(w=>w.id)];
  document.getElementById('taskbar').innerHTML=`<span class="managed-taskbar">WORK PROFILE</span><div class="taskbar-center"><button class="taskbar-system" data-final="start" aria-label="Start">${WinShell.logo()}</button><div class="taskbar-apps">${tabs.map(id=>`<button class="taskbar-app ${Desktop.win(id)?'running':''} ${comp.front===id?'selected':''}" data-taskbar="${id}" aria-label="${esc(apps[id].name)}" title="${esc(apps[id].name)}">${WinShell.appIcon(symbol(id))}</button>`).join('')}</div></div><div class="system-tray"><span class="input-language">EN</span><button class="tray-date" data-final="notifications" aria-label="Work notifications"><span class="desktop-clock"><strong>${f.clock}</strong><small>Monday · again</small></span>${icon('bell')}${!f.notificationRead?'<i></i>':''}</button><button class="show-desktop-edge" data-desktop="show-desktop" aria-label="Show desktop"></button></div>`;
  renderDeadlines();
  const front=Desktop.win(comp.front);document.body.style.setProperty('--notification-top',((front?(front.max||innerWidth<700?8:front.y):0)+60)+'px');
 }
 const deadlines=[
  {id:'report',time:'12:00',title:'FINAL REPORT',text:'Client wants the numbers again. Send v18 before lunch.',app:'file-0'},
  {id:'revision',time:'17:20',title:'FINAL, FINAL VERSION',text:'Do not clock out before the last revision is submitted.',app:'log'},
  {id:'summary',time:'18:30',title:'TONIGHT’S SUMMARY',text:'Compile the new requests. The meeting was moved earlier.',app:'file-1'},
  {id:'capacity',time:'23:59',title:'PERFORMANCE CHECK',text:'Today’s target is the minimum. Tomorrow: 120.',app:'targets'},
  {id:'available',time:'ASAP',title:'STAY AVAILABLE',text:'Manager: “Just one more thing.” Keep Workspace open.',app:'manager'}
 ];
 const notePositions={};let noteDrag=null;
 function notePosition(i){
  const small=innerWidth<700, compact=innerWidth<1050;
  const nw=small?166:compact?185:220, nh=small?152:170;
  const positions=small?[[innerWidth-nw-15,120],[innerWidth-nw-26,310],[innerWidth-nw-16,500],[18,410],[24,610]]:
   [[innerWidth-nw-25,96],[innerWidth-nw-45,285],[innerWidth-nw-20,480],[Math.max(280,innerWidth-nw*2-90),innerHeight-245],[Math.max(190,innerWidth-nw*3-125),innerHeight-220]];
  const [x,y]=positions[i];return {x:Math.max(5,Math.min(x,innerWidth-nw-8)),y:Math.max(50,Math.min(y,innerHeight-nh-65))};
 }
 function renderDeadlines(){
  let board=document.getElementById('deadline-board');
  if(!board){board=document.createElement('aside');board.id='deadline-board';board.setAttribute('aria-label','Deadline sticky notes');document.getElementById('desktop').append(board);}
  if(!board.children.length)board.innerHTML=deadlines.map((n,i)=>`<section class="ddl-note" data-note="${n.id}" style="--tilt:${[-2,2,-1,2,-3][i]}deg"><button class="ddl-handle" aria-label="Move ${n.title} deadline reminder">DEADLINE <span>⠿</span></button><button class="ddl-body" data-final="open" data-id="${n.app}"><strong>${n.time}</strong><b>${n.title}</b><p>${n.text}</p><small>${i===1?'Work Log · <span data-note-target></span>':'Open attachment ↗'}</small></button></section>`).join('');
  deadlines.forEach((n,i)=>{const el=board.querySelector(`[data-note="${n.id}"]`),pos=notePositions[n.id]||notePosition(i);el.style.left=pos.x+'px';el.style.top=pos.y+'px';});
  board.querySelector('[data-note-target]').textContent=metric();
 }
 document.addEventListener('pointerdown',e=>{const handle=e.target.closest('.ddl-handle');if(!handle)return;const note=handle.closest('.ddl-note');noteDrag={id:note.dataset.note,x:e.clientX,y:e.clientY,left:parseFloat(note.style.left),top:parseFloat(note.style.top)};handle.setPointerCapture(e.pointerId);e.preventDefault();});
 document.addEventListener('pointermove',e=>{if(!noteDrag)return;const el=document.querySelector(`[data-note="${noteDrag.id}"]`);const pos={x:Math.max(0,Math.min(noteDrag.left+e.clientX-noteDrag.x,innerWidth-el.offsetWidth)),y:Math.max(45,Math.min(noteDrag.top+e.clientY-noteDrag.y,innerHeight-el.offsetHeight-50))};notePositions[noteDrag.id]=pos;el.style.left=pos.x+'px';el.style.top=pos.y+'px';});
 document.addEventListener('pointerup',()=>{noteDrag=null;});
 document.addEventListener('pointercancel',()=>{noteDrag=null;});
 document.addEventListener('keydown',e=>{const handle=e.target.closest('.ddl-handle');if(!handle||!e.key.startsWith('Arrow'))return;e.preventDefault();const el=handle.closest('.ddl-note'),pos={x:parseFloat(el.style.left),y:parseFloat(el.style.top)};pos.x+=e.key==='ArrowRight'?15:e.key==='ArrowLeft'?-15:0;pos.y+=e.key==='ArrowDown'?15:e.key==='ArrowUp'?-15:0;pos.x=Math.max(0,Math.min(pos.x,innerWidth-el.offsetWidth));pos.y=Math.max(45,Math.min(pos.y,innerHeight-el.offsetHeight-50));notePositions[el.dataset.note]=pos;el.style.left=pos.x+'px';el.style.top=pos.y+'px';});
 function toolbar(path,right='Organization workspace'){return `<div class="final-toolbar"><span>${path}</span><span>${right}</span></div>`;}
 function logView(){
  const rows=['Revise project report','Send client update','Archive approved files','Confirm meeting notes'];
  return `${toolbar('Work / Records / Work Log',f.saved?'Work record saved':'Unsaved work log')}<div class="final-document"><div class="document-heading"><div><span class="eyebrow">MONDAY / EMPLOYEE 0247</span><h1>Work Log</h1><p class="muted">Yesterday’s work has been carried forward.</p></div><span class="final-stamp">${f.cycle?'AUTO-RESTORED':'REVISION 247'}</span></div><div class="log-metric"><div><span>Daily target</span><strong>${metric()}</strong></div><p>${f.submitted?'Previous target met. Your capacity has been updated.':f.cycle?'A new day. The same files.':'One more submission to complete today’s target.'}</p></div><div class="final-progress"><i style="width:${f.score/f.target*100}%"></i></div><table class="final-table"><thead><tr><th>Work record</th><th>Time</th><th>Status</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${x}</td><td>09:00</td><td><span class="quiet-chip">Recorded × ${23+i}</span></td></tr>`).join('')}<tr class="pending-row"><td>${f.cycle?'Project report_v248.docx':'Project report_final_REVISED_12.docx'}</td><td>${f.cycle?'09:00':'17:20'}</td><td>${f.submitted?'Submitted':f.cycle?'Assigned':'Pending · +1'}</td></tr></tbody></table>${f.submitted?'<div class="system-receipt"><b>100 / 100 — target completed.</b><span>New daily target: 120. Another 20 units have been assigned.</span></div>':f.cycle?'<div class="system-receipt"><b>Session restored automatically.</b><span>The next report is already waiting in Workspace.</span></div>':''}<label class="final-note-label" for="final-note">Work notes <span>Work-related entries only</span></label><textarea id="final-note" placeholder="Add a work note…">${esc(f.draft)}</textarea></div><footer class="final-actions log-actions">${!f.submitted&&!f.cycle?`<label class="final-check"><input type="checkbox" data-final-check ${f.reviewed?'checked':''}>I have reviewed the final revision and its attachments.</label>`:''}<div class="log-action-row"><span>${f.saved?'Work record saved.':f.cycle?'Personal session not restored.':'Last saved: Monday, 09:00'}</span><div><button class="btn" data-final="save">Save work log</button>${!f.submitted&&!f.cycle?`<button class="btn primary" data-final="submit" ${!f.reviewed?'disabled':''}>Submit final item · +1</button>`:`<button class="btn primary" data-final="shutdown">Shut down</button>`}</div></div></footer>`;
 }
 function managerView(){return `${toolbar('Workspace / Manager','12 follow-ups · 0 personal notifications')}<div class="final-chat"><aside class="final-contacts"><span class="eyebrow">WORKSPACE</span><button class="selected" data-final="manager"><b class="avatar">M</b><span>Manager<small>Always available</small></span></button><div class="contact-static"><b class="avatar">S</b><span>Task system<small>Automatic assignment</small></span></div><p>External contacts hidden by work profile.</p>${button('archive','Archived contacts','archive-link')}</aside><section class="final-conversation"><header><strong>Manager</strong><small>Project communication · Required</small></header><div class="final-messages"><div class="chat-time">Monday · ${f.cycle?'09:00':'17:20'}</div><div class="final-bubble">${f.cycle?'Morning. The client sent two changes. I’ve marked them in the report. Could you update it before lunch?':'Good work on the last batch. Please finish the final revision before you leave.'}${button('log',`${icon('file')} Work Log · ${metric()}`,'final-attachment')}</div><div class="final-bubble">${f.cycle?'Your new daily target is 120. Yesterday’s queue has been restored.':'The next deadline is also today. I’ve put the remaining versions on your desktop.'}</div>${f.submitted?'<div class="final-bubble system">Target completed: 100 / 100.<br>Performance baseline adjusted to 120.</div><div class="final-bubble">Thanks. Since you can handle more, I’ve assigned another 20. Please stay available.</div>':''}${f.reply?'<div class="final-bubble mine">Received. I’ll continue.</div><div class="final-bubble">Noted. Please update the work log.</div>':''}</div><footer><button class="btn" data-final="reply" ${f.reply?'disabled':''}>${f.reply?'Acknowledgement sent':'Received. I’ll continue.'}</button><small>Availability: managed by your organization</small></footer></section></div>`;}
 function queueView(){return `${toolbar('This PC / Desktop / Work','60 files · All due today')}<div class="final-file-header"><h2>Assigned files</h2><p>Every version is marked final.</p></div><div class="final-file-list"><div class="file-list-head"><span>Name</span><span>Modified</span><span>Status</span></div>${files.map(x=>`<button data-final="open" data-id="${x.id}"><span>${WinShell.appIcon('document')}${esc(x.name)}</span><span>Monday 09:00</span><span>Required</span></button>`).join('')}</div><div class="file-bottom">Personal folders moved to managed archive.</div>`;}
 function fileView(w){return `${toolbar('Work / Attachments / '+esc(apps[w.app].name),'Read-only source')}<div class="final-document"><span class="eyebrow">PROJECT COLLABORATION</span><h1>${esc(apps[w.app].name.split('.')[0].replaceAll('_',' '))}</h1><p class="muted">Owner: Employee 0247 · Due: today · Version supersedes previous final</p><table class="final-table"><tr><th>Requested change</th><th>Requirement</th></tr><tr><td>Recheck the request count</td><td>38 requests / 31 scheduled</td></tr><tr><td>Carry forward previous notes</td><td>Repeat the approved wording</td></tr><tr><td>Confirm availability</td><td>Until all revisions are complete</td></tr></table><div class="system-receipt"><b>One more revision.</b><span>This attachment has the same instructions as the previous version.</span></div><p class="muted">Completion is recorded in the Work Log.</p></div><footer class="final-actions"><span>Required · Assigned automatically</span>${button('log','Open Work Log','btn primary')}</footer>`;}
 function archiveView(){const yuan=f.contact!=='notes';return `${toolbar('This PC / Personal / Archived','Last activity: 247 days ago')}<div class="final-chat archived-chat"><aside class="final-contacts"><span class="eyebrow">KEPT LOCALLY</span><button data-final="archive-yuan" class="${yuan?'selected':''}"><b class="avatar">Y</b><span>Yuan<small>Last seen long ago</small></span></button><button data-final="archive-notes" class="${!yuan?'selected':''}"><b class="avatar">N</b><span>Weekend notes<small>Never completed</small></span></button></aside><section class="final-conversation"><header><strong>${yuan?'Yuan':'Things to do this weekend'}</strong><small>${yuan?'Personal contact · Archived':'Personal notes · Read only'}</small></header><div class="final-messages">${yuan?'<div class="chat-time">247 days ago · 17:20</div><div class="final-bubble">Same place at six thirty? I’ll bring the ball. Just come straight over.</div><div class="chat-time">246 days ago · 18:42</div><div class="final-bubble">No worries. Maybe next time.</div><div class="chat-time">No recent messages</div>':'<div class="archived-notes">Repot the plant.<br>Finish the sketch of the lake.<br>Finish reading Invisible Cities.<br><br>Yuan says the lights at the new court are good.<br>Let’s try it next time.</div>'}</div><footer><span class="archive-blocked">${icon('info')} ${yuan?'Messaging is unavailable in this work profile.':'Personal notes cannot be edited in this work profile.'}</span></footer></section></div>`;}
 function policyView(id){const personal=['photosOld','gamesOld','musicOld'].includes(id);return `${toolbar('Settings / Managed device','Organization policy')}<div class="final-document"><span class="eyebrow">EMPLOYEE 0247</span><h1>${personal?apps[id].name.split(' —')[0]+' is unavailable':'This device is managed'}</h1><p>${personal?'This personal application is no longer available in your work profile.':'Your organization controls this computer’s background, applications and active hours.'}</p><div class="policy-row"><span>Account</span><b>Employee 0247</b></div><div class="policy-row"><span>Personalization</span><b>Locked</b></div><div class="policy-row"><span>Personal applications</span><b>Archived or removed</b></div><div class="policy-row"><span>Active hours</span><b>09:00 — until complete</b></div><div class="policy-row"><span>Restore work after shutdown</span><b>Always on</b></div><p class="muted">Some shortcuts may still point to applications that are no longer here.</p>${button('archive','View remaining personal files')}</div>`;}
 function targetView(){return `${toolbar('Performance / Capacity review','Updated automatically')}<div class="final-document"><span class="eyebrow">PERFORMANCE HISTORY</span><h1>Meeting the target<br>sets the next one.</h1><p class="muted">Daily requirements · Employee 0247</p><div class="target-history">${[20,25,50,75,100,120].map((n,i)=>`<div><span>${i===0?'First Monday':i===5?'Next baseline':'Review '+i}</span><i style="width:${n/120*52}%"></i><b>${n}</b></div>`).join('')}</div><div class="system-receipt"><b>Current progress: ${metric()}</b><span>Completed work is used to calculate additional capacity.</span></div></div>`;}
 function calendarView(){return `${toolbar('Calendar / Monday','All day · Work')}<div class="final-document"><span class="eyebrow">MONDAY / MONDAY / MONDAY</span><h1>No free time found.</h1><div class="work-schedule">${[['09:00','Revise report'],['11:10','Reply to client'],['14:30','Archive revisions'],['17:20','One more task'],['18:30','Reserved for work'],['19:40','Complete remaining queue']].map(([t,s])=>`<div><time>${t}</time><span>${s}<small>Work · Required</small></span></div>`).join('')}</div><p class="muted">Personal events are no longer synced.</p></div>`;}
 function view(w){switch(w.app){case 'log':return logView();case 'manager':return managerView();case 'queue':return queueView();case 'archive':return archiveView();case 'targets':return targetView();case 'calendarWork':return calendarView();case 'policy':case 'photosOld':case 'musicOld':case 'gamesOld':return policyView(w.app);default:return fileView(w);}}
 function refresh(){for(const w of Desktop.comp().windows)Desktop.renderWindow(w);chrome();persist();}
 function hidePanels(){for(const id of ['system-menu','notification-center','desktop-context','quick-settings'])document.getElementById(id).hidden=true;}
 function onFocus(id){if(id==='manager'){f.notificationRead=true;clearTimeout(noticeTimer);document.getElementById('banners').replaceChildren();}}
 function open(id){hidePanels();Desktop.openApp(id);}
 function notice(text){
  clearTimeout(noticeTimer);document.getElementById('banners').innerHTML=`<div class="notification-banner final-notification"><header>${WinShell.appIcon('office')}<span>Workspace · Manager</span><button data-final="dismiss" aria-label="Dismiss notification">${icon('close')}</button></header><button class="final-notification-body" data-final="open" data-id="manager"><strong>${f.cycle?'09:00 · Morning.':'A new assignment'}</strong><p>${text}</p><small>Open Workspace →</small></button></div>`;
  // Keep the cue visible for a presenter; it only disappears after an explicit action.
 }
 function start(){const m=document.getElementById('system-menu'),show=m.hidden;hidePanels();m.hidden=!show;m.innerHTML=`<div class="final-start-account"><b>0247</b><span>Employee 0247<small>Organization-managed device</small></span></div><div class="start-heading"><strong>Required apps</strong><span>Managed</span></div><div class="start-app-grid">${['log','manager','queue','targets','calendarWork','policy'].map(id=>`<button data-final="open" data-id="${id}">${WinShell.appIcon(symbol(id))}<span>${apps[id].name}</span></button>`).join('')}</div><div class="start-heading"><strong>Recommended</strong><span>Same as yesterday</span></div><div class="start-recent">${files.slice(0,4).map(x=>`<button data-final="open" data-id="${x.id}">${WinShell.appIcon('document')}<span>${esc(x.name)}<small>Due today</small></span></button>`).join('')}</div><footer class="start-footer"><span class="local-account">Personal profile unavailable</span><button class="btn" data-final="shutdown">${icon('logout')} Shut down</button></footer>`;}
 function notifications(){const c=document.getElementById('notification-center'),show=c.hidden;hidePanels();c.hidden=!show;c.innerHTML=`<div class="final-notifications-head"><h3>Work notifications</h3><button data-final="close-panels" aria-label="Close notifications">${icon('close')}</button></div>${['Please finish the final revision.','Deadline reminder: today.','Another file has been assigned.','Your availability has been extended.','Capacity review is ready.'].map((s,i)=>`<button class="final-notice-row" data-final="open" data-id="${i===4?'targets':'manager'}"><b>${i===4?'Performance':'Workspace · Manager'}</b><span>${s}</span><small>${f.clock} · Monday</small></button>`).join('')}<p class="muted">No recent personal notifications.</p>`;}
 function submit(){
  if(!f.reviewed||f.submitted||f.cycle)return;
  f.submitted=true;f.score=100;f.target=120;f.saved=false;f.notificationRead=false;
  refresh();notice('Thanks. Your daily target is now 120. Another 20 units are waiting.');
  document.getElementById('announcement').textContent='Target completed. New daily target: 120.';
 }
 function shutdown(){
  if(f.busy)return;f.busy=true;hidePanels();document.getElementById('banners').replaceChildren();
  const overlay=document.createElement('div');overlay.id='final-blackout';overlay.setAttribute('role','status');overlay.setAttribute('aria-live','polite');overlay.innerHTML='<div><span class="boot-dot"></span><p>Shutting down</p></div>';document.body.append(overlay);
  setTimeout(()=>{overlay.innerHTML='<div><strong>09:00</strong><p>Restoring your workspace.</p></div>';},1600);
  setTimeout(()=>{
   f.cycle++;f.clock='09:00';f.score=0;f.target=120;f.submitted=false;f.reviewed=false;f.reply=false;f.saved=true;f.busy=false;f.notificationRead=false;
   state.clock=f.clock;Desktop.clearWindows();chrome();persist();overlay.remove();open('log');notice('The client sent two changes. Please update the report before lunch.');
   document.getElementById('announcement').textContent='Monday, 09:00. Your workspace has been restored. Daily target: 120.';
  },3800);
 }
 function context(e){if(e.target.closest('.app-window,#taskbar,#system-menu,#notification-center'))return;e.preventDefault();hidePanels();const m=document.getElementById('desktop-context');m.hidden=false;m.style.left=Math.max(4,Math.min(e.clientX,innerWidth-254))+'px';m.style.top=Math.max(4,Math.min(e.clientY,innerHeight-170))+'px';m.innerHTML=`<button data-desktop="show-desktop">${icon('dashboard')}Show desktop</button><button data-final="open" data-id="policy">${icon('settings')}Managed device settings</button><button data-final="shutdown">${icon('logout')}Shut down</button>`;}
 function init(){
  const computer=state.computer;state={...freshState(),computer,openingShown:true,copyLocale:'en',finalStory:f};state.clock=f.clock;state.workMessages=[];state.privateMessages=[];
  chrome();const hint=document.createElement('aside');hint.id='entry-guide';hint.innerHTML=`<button class="entry-close" data-desktop="entry-close" aria-label="Dismiss the welcome tip">${icon('close')}</button><strong>Session 247 · Still Monday</strong><p>Your last task is waiting. Everything else has been moved out of the way.</p><div class="entry-actions">${button('log','Continue in Work Log','btn primary')}${button('archive','Personal archive')}</div><small>Double-click a file, or use the taskbar. Shut down from Start.</small>`;document.getElementById('desktop').append(hint);
  persist();
  if(location.protocol.startsWith('http')&&new URLSearchParams(location.search).has('restart'))history.replaceState(null,'',location.pathname);
  noticeTimer=setTimeout(()=>notice(f.cycle?'Morning. Your work has been restored.':f.submitted?'Another 20 units are waiting. Please stay available.':'One more revision before you leave. Please open your Work Log.'),1200);
 }
 document.addEventListener('change',e=>{if(e.target.matches('[data-final-check]')){f.reviewed=e.target.checked;persist();const submitButton=document.querySelector('[data-final="submit"]');if(submitButton)submitButton.disabled=!f.reviewed;}});
 document.addEventListener('input',e=>{if(e.target.id==='final-note'){f.draft=e.target.value;f.saved=false;persist();}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-final]');if(!b||b.disabled)return;switch(b.dataset.final){
  case 'open':open(b.dataset.id);break;case 'submit':submit();break;
  case 'save':f.saved=true;refresh();toast('Work record saved.');break;
  case 'reply':f.reply=true;refresh();break;
  case 'archive-yuan':f.contact='yuan';refresh();break;case 'archive-notes':f.contact='notes';refresh();break;
  case 'manager':open('manager');break;case 'start':start();break;case 'notifications':notifications();break;
  case 'shutdown':shutdown();break;case 'close-panels':hidePanels();break;case 'dismiss':document.getElementById('banners').replaceChildren();break;
 }});
 window.render_game_to_text=()=>JSON.stringify({part:'final',clock:f.clock,day:'Monday',performance:f.score,target:f.target,submitted:f.submitted,reviewed:f.reviewed,cycle:f.cycle,booting:f.busy,workLogSaved:f.saved,personalApps:'unavailable',workFiles:files.length,deadlineNotes:deadlines.length,wallpaper:'AI-generated personal work desk, performance trophy, deadlines and executive photos',front:typeof Desktop==='undefined'?null:Desktop.comp().front,windows:typeof Desktop==='undefined'?[]:Desktop.comp().windows.map(w=>({id:w.id,min:w.min,max:w.max})),coordinateSystem:'top-left origin; x right, y down'});
 window.advanceTime=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 return {apps,iconFor:symbol,title:w=>apps[w.app].name,place,chrome,view,init,context,onFocus};
})();
