'use strict';
const WinShell=(()=>{
 const wallpapers=[{file:'bloom-light.jpg',name:'Windows 11 · Bloom Light'},{file:'bloom-dark.jpg',name:'Windows 11 · Bloom Dark'},{file:'bloom-hub.png',name:'Surface Hub · Blue-violet waves'}];
 const designs={
 office:'<path fill="#267bdd" d="M5 6h23v27H5z"/><path fill="#57b9fb" d="m20 3 15 7v22l-15 5z"/><path fill="#fff" d="m10 15 5 5 13-10v7L15 27l-5-6z"/>',
 chat:'<path fill="#28b86b" d="M3 6h28v21H15l-8 7v-7H3z"/><path fill="#a1efb6" d="M19 14h17v17h-5l-1 5-6-5h-5z"/><circle fill="#fff" cx="10" cy="17" r="2"/><circle fill="#fff" cx="17" cy="17" r="2"/>',
 email:'<path fill="#146cd2" d="M7 4h26v29H7z"/><path fill="#55b7f4" d="M2 15h35v20H2z"/><path fill="#92dbff" d="m2 15 18 12 17-12z"/><path fill="#268be0" d="m2 35 12-12 6 4 5-4 12 12z"/>',
 calendar:'<rect fill="#fff" x="5" y="5" width="30" height="31" rx="2"/><path fill="#2080d8" d="M5 5h30v10H5z"/><path stroke="#a9daff" stroke-width="3" d="M12 3v6M28 3v6"/><path fill="#287bc7" d="M11 20h5v5h-5zM22 20h5v5h-5zM11 28h5v4h-5zM22 28h5v4h-5z"/>',
 files:'<path fill="#e4a125" d="M2 9h14l4 5h17v20H2z"/><path fill="#ffd366" d="M2 15h35l-3 20H2z"/><path fill="#ffe6a0" d="M6 12h26v4H6z"/>',
 games:'<circle fill="#16843d" cx="20" cy="20" r="18"/><path fill="#eefbf1" d="M11 12h18c5 0 8 15 3 17-3 1-6-5-8-5h-8c-2 0-5 6-8 5-5-2-2-17 3-17z"/><path stroke="#308e50" stroke-width="2" d="M12 16v8m-4-4h8"/><circle fill="#308e50" cx="26" cy="17" r="1.5"/><circle fill="#308e50" cx="30" cy="21" r="1.5"/>',
 music:'<circle fill="#ed6838" cx="20" cy="20" r="18"/><circle fill="#ffab40" cx="20" cy="20" r="14"/><path fill="#fff" d="M18 9v17a4 4 0 1 1-3-4V11l13-3v15a4 4 0 1 1-3-4V12z"/>',
 photos:'<rect fill="#2798e8" x="7" y="3" width="29" height="27" rx="2"/><rect fill="#61bff0" x="2" y="10" width="30" height="27" rx="2"/><circle fill="#fbe2ac" cx="23" cy="17" r="4"/><path fill="#1646a5" d="m2 31 10-12 12 18H2z"/><path fill="#5d87d9" d="m15 37 9-12 8 8v4z"/>',
 notes:'<path fill="#f5cb46" d="M4 4h31v25l-8 8H4z"/><path fill="#ffe98e" d="M4 9h31v20l-8 8H4z"/><path fill="#dcb43d" d="M27 29h8l-8 8z"/><path stroke="#bea14d" stroke-width="1.5" d="M10 16h19M10 22h17M10 28h12"/>',
 document:'<path fill="#e7f2ff" d="M8 2h17l9 9v27H8z"/><path fill="#85b7eb" d="M25 2v9h9z"/><path fill="#266ac6" d="M3 13h18v20H3z"/><path stroke="#fff" stroke-width="1.4" d="m7 18 2 10 3-7 3 7 2-10"/><path stroke="#7aa0cc" stroke-width="2" d="M24 18h6M24 24h6M24 30h6"/>',
 settings:'<path fill="#7c8d9c" d="m16 2 8 0 2 5 5 2 5 1 3 8-4 4-1 5-1 5-8 4-4-3-5-1-5-1-4-8 3-5 1-5z"/><circle fill="#d9e4ec" cx="20" cy="20" r="10"/><circle fill="#3899dc" cx="20" cy="20" r="6"/>'
 };
 function appIcon(id){return `<span class="app-icon fluent-icon"><svg viewBox="0 0 40 40" aria-hidden="true">${designs[id]||designs.document}</svg></span>`;}
 const logo=()=>'<svg class="windows-logo" viewBox="0 0 24 24" aria-hidden="true"><path fill="#0078d4" d="M1 1h10v10H1zM13 1h10v10H13zM1 13h10v10H1zM13 13h10v10H13z"/></svg>';
 const wifi=()=>'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8q9-7 18 0M6 12q6-5 12 0M9 16q3-3 6 0"/><circle cx="12" cy="20" r=".7"/></svg>';
 const power=()=>'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2v10M7 5a8 8 0 1 0 10 0"/></svg>';
 function closePanels(){for(const id of ['system-menu','desktop-context','quick-settings','notification-center'])document.getElementById(id).hidden=true;}
 function toggleStart(search=false){const m=document.getElementById('system-menu'),open=m.hidden||search;closePanels();m.hidden=!open;if(!open)return;m.innerHTML=`<div class="start-search">${icon('search')}<input id="start-search" placeholder="Search apps" aria-label="Search apps"></div><div class="start-heading"><strong>Pinned</strong><button data-desktop="all-apps">All apps ${icon('chevron')}</button></div><div class="start-app-grid">${Object.entries(Desktop.apps).map(([id,a])=>`<button data-desktop="start-app" data-app="${id}" data-name="${a.name}">${appIcon(id)}<span>${a.name}</span></button>`).join('')}</div><div class="start-heading"><strong>Recommended</strong><span>Recently opened</span></div><div class="start-recent"><button data-desktop="recent-report">${appIcon('document')}<span>Project report_v3.docx<small>Work files · Monday</small></span></button><button data-desktop="start-app" data-app="notes">${appIcon('notes')}<span>Things to do this weekend<small>Personal notes</small></span></button><button data-desktop="start-app" data-app="photos">${appIcon('photos')}<span>Weekend album<small>3  photos</small></span></button><button data-action="help">${appIcon('settings')}<span>Help and saved progress<small>About this computer</small></span></button></div><footer class="start-footer"><span class="local-account"><span>Me</span>Local user</span><button data-desktop="power-menu" aria-label="Power">${power()}</button></footer><div class="power-menu" hidden><button data-action="${state.stage==='night'?'sleep':'leave'}" ${state.stage==='tuesday'?'disabled':''}>${power()}${state.stage==='night'?'Close the laptop and rest':'Leave computer'}</button><button data-desktop="show-desktop">Show desktop</button></div>`;if(search)m.querySelector('input').focus();}
 function settings(){const selected=wallpapers.find(w=>w.file===Desktop.comp().wallpaper)||wallpapers[0];return `<div class="settings-layout"><aside class="settings-sidebar"><div class="settings-user"><b>Me</b><span>Local user<small>Personal computer</small></span></div><button class="active">${icon('photo')}Personalization</button><button data-action="help">${icon('info')}Help and saved progress</button></aside><section class="settings-main"><h1>Personalization <span>›</span> Background</h1><div class="background-preview" style="background-image:url('assets/wallpapers/${selected.file}')"><div></div></div><div class="setting-row"><span><strong>Personalize your background</strong><small>Choose a desktop background</small></span><span class="setting-value">Picture⌄</span></div><h3>Choose photo</h3><div class="wallpaper-options">${wallpapers.map(w=>`<button data-desktop="wallpaper" data-wallpaper="${w.file}" aria-label="${w.name}" aria-pressed="${w.file===selected.file}"><img src="assets/wallpapers/${w.file}" alt="${w.name}"><span>${w.name}</span></button>`).join('')}</div><p class="wallpaper-note">${selected.name}</p><div class="setting-row"><span>Choose how the image fits your desktop.</span><span class="setting-value">Fill</span></div></section></div>`;}
 function quickSettings(){const q=document.getElementById('quick-settings'),open=q.hidden;closePanels();q.hidden=!open;if(!open)return;q.innerHTML=`<h3>Quick settings</h3><button class="sound-tile ${Desktop.comp().sound?'enabled':''}" data-desktop="toggle-sound">${icon('volume')}<span>Notification sounds · ${Desktop.comp().sound?'On':'Off'}</span></button><p>Message sound: WeChat desktop notification (W01)</p><button class="btn" data-desktop="preview-notification">Preview sound</button><p>Music playback is controlled separately in the Music app.</p><footer><span>Local experience</span><button data-desktop="start-app" data-app="settings" aria-label="Open settings">${appIcon('settings')}</button></footer>`;}
 function action(a,el){switch(a){case 'start-app':closePanels();Desktop.openApp(el.dataset.app);return true;case 'all-apps':{const grid=document.querySelector('.start-app-grid');grid.classList.add('all-apps-list');el.dataset.desktop='pinned-apps';el.textContent='Back';el.parentElement.querySelector('strong').textContent='All apps';return true;}case 'pinned-apps':{document.querySelector('.start-app-grid').classList.remove('all-apps-list');el.dataset.desktop='all-apps';el.textContent='All apps ›';el.parentElement.querySelector('strong').textContent='Pinned';return true;}case 'recent-report':closePanels();Desktop.openDocument('report');return true;case 'power-menu':{const m=document.querySelector('.power-menu');m.hidden=!m.hidden;return true;}case 'personalize':closePanels();Desktop.openApp('settings');return true;case 'wallpaper':Desktop.comp().wallpaper=el.dataset.wallpaper;persist();Desktop.chrome();Desktop.renderWindow(Desktop.win('settings'));return true;case 'preview-notification':Leisure.unlock(true);return true;case 'toggle-sound':Desktop.comp().sound=!Desktop.comp().sound;if(Desktop.comp().sound)Leisure.unlock(true);else Leisure.muteNotifications();persist();document.getElementById('quick-settings').hidden=true;quickSettings();return true;case 'desktop-refresh':closePanels();Desktop.chrome();return true;}return false;}
 document.addEventListener('contextmenu',e=>{if(!e.target.closest('#desktop')||e.target.closest('.app-window,#taskbar,#system-menu,#notification-center'))return;e.preventDefault();closePanels();const m=document.getElementById('desktop-context');m.hidden=false;m.style.left=Math.max(4,Math.min(e.clientX,innerWidth-254))+'px';m.style.top=Math.max(4,Math.min(e.clientY,innerHeight-225))+'px';m.innerHTML=`<button data-desktop="show-desktop">${icon('dashboard')}Show desktop</button><button data-desktop="desktop-refresh">${icon('reset')}Refresh</button><hr><button data-desktop="personalize">${icon('photo')}Personalization</button><button data-action="help">${icon('info')}Help and saved progress</button>`;});
 document.addEventListener('input',e=>{if(e.target.id==='start-search'){const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.start-app-grid button').forEach(b=>b.hidden=!b.dataset.name.toLowerCase().includes(q));}});
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('#system-menu,#desktop-context,#quick-settings,#notification-center,[data-desktop="menu"],[data-desktop="search"],[data-desktop="notifications"],[data-desktop="quick-settings"]'))closePanels();});
 document.addEventListener('click',e=>{if(e.target.closest('[data-desktop="show-desktop"],[data-action]'))closePanels();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels();});
 return {wallpapers,appIcon,logo,wifi,toggleStart,settings,quickSettings,action};
})();
